import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Pencil, Plus, Tags, Trash2 } from "lucide-react";
import { toast } from "sonner";

export default function ProductTypes() {
  const utils = trpc.useUtils();
  const [open, setOpen] = useState(false); const [id, setId] = useState<number | null>(null); const [name, setName] = useState(""); const [deleteId, setDeleteId] = useState<number | null>(null);
  const { data: types, isLoading } = trpc.productTypes.list.useQuery();
  const reset = () => { setOpen(false); setId(null); setName(""); };
  const create = trpc.productTypes.create.useMutation({ onSuccess: () => { utils.productTypes.list.invalidate(); toast.success("Tipo cadastrado"); reset(); }, onError: (e) => toast.error(e.message) });
  const update = trpc.productTypes.update.useMutation({ onSuccess: () => { utils.productTypes.list.invalidate(); utils.products.list.invalidate(); toast.success("Tipo atualizado"); reset(); }, onError: (e) => toast.error(e.message) });
  const remove = trpc.productTypes.delete.useMutation({ onSuccess: () => { utils.productTypes.list.invalidate(); setDeleteId(null); toast.success("Tipo removido"); }, onError: (e) => toast.error(e.message) });
  const save = () => { if (!name.trim()) { toast.error("Informe o nome do tipo"); return; } if (id) update.mutate({ id, name }); else create.mutate({ name }); };
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold">Tipos de Produto</h1><p className="text-sm text-muted-foreground">Mantenha a lista usada no cadastro de Produtos.</p></div><Dialog open={open} onOpenChange={(value) => value ? setOpen(true) : reset()}><DialogTrigger asChild><Button><Plus className="mr-2 h-4 w-4" />Novo tipo</Button></DialogTrigger><DialogContent className="max-w-[calc(100vw-2rem)] sm:max-w-md"><DialogHeader><DialogTitle>{id ? "Editar tipo" : "Novo tipo de produto"}</DialogTitle></DialogHeader><div className="space-y-2 py-4"><label className="text-sm font-medium">Nome *</label><Input autoFocus value={name} onChange={(e) => setName(e.target.value)} placeholder="Ex.: Vidro temperado" /></div><div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button className="w-full sm:w-auto" variant="outline" onClick={reset}>Cancelar</Button><Button className="w-full sm:w-auto" onClick={save} disabled={create.isPending || update.isPending}>{create.isPending || update.isPending ? "Salvando..." : "Salvar"}</Button></div></DialogContent></Dialog></div><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Tags className="h-4 w-4" />Tipos disponíveis</CardTitle></CardHeader><CardContent className="p-0">{isLoading ? <div className="p-8 text-center text-muted-foreground">Carregando...</div> : !types?.length ? <div className="p-8 text-center text-muted-foreground">Nenhum tipo cadastrado.</div> : <Table><TableHeader><TableRow><TableHead>Tipo</TableHead><TableHead className="w-[100px]">Ações</TableHead></TableRow></TableHeader><TableBody>{types.map((type) => <TableRow key={type.id}><TableCell className="font-medium">{type.name}</TableCell><TableCell><div className="flex gap-1"><Button variant="ghost" size="icon" aria-label={`Editar ${type.name}`} onClick={() => { setId(type.id); setName(type.name); setOpen(true); }}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" className="text-destructive" aria-label={`Excluir ${type.name}`} onClick={() => setDeleteId(type.id)}><Trash2 className="h-4 w-4" /></Button></div></TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card><AlertDialog open={deleteId !== null} onOpenChange={(value) => !value && setDeleteId(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Excluir tipo</AlertDialogTitle><AlertDialogDescription>Tipos vinculados a produtos não podem ser removidos.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={() => deleteId && remove.mutate({ id: deleteId })} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">Excluir</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
